version: 0.2


phases:
  install:
    runtime-version:
      nodejs: 10
    commands:
      - echo "Hello there"
  pre_build:
    commands:
      - echo "this is the pre-build stage"
  build:
    commands:
      - echo "this is the build stage"

  post_build:
    commands:
      - echo "this is the post build stage"

